version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgresArv
    ports:
      - '2612:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./app.env


  redis:
    image: redis:alpine3.18
    container_name: redisArv
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  progresDB:
  redis_data: